language: node_js
node_js: "7"
deploy:
  provider: firebase
  token:
    secure: "fICHC913WWwhpU+twtoTKkI9I8r83OLdb3wwY6/Gs1BKNyGeQtvH2k6aJJ5owLSC2oYPvTlfvgEKH10uxMeSummBdHyowRkpDtYAwEUyY4aFj+qohP1PUTDnEXk54Et2cHrVpx4JI+Ne+5EqwHMb4SqRMgqXhX+8W3I6+xfoEMXXVSWRy2pTQ4zMAivD/cNd8zcTvCPO1uI43++mtqxe8EguvEBL1HmZktWtYWmvgn3UPuS1zlRLSRhmVN46+lTUtN80Y1HubR4G0MOQQ/3speG1O7K9ENSEyiG+pfCZn10nhLzELb6LY8GoXeciw9tUTFVDO9lgkOr7L3fVcD0BHQ/oAVpNyD8b3rqywiKpI/nMPT5lIxeZ4akdb0R+HXmayKYQ+BPIdfBr4pXx9ASKfElQCEz40541S6oj6CuvxuPsIxqrAAckzBWz6lT78R/UsMRkCr3HRt93MZkq24IDKONiSCa6r/haoFp6GpQy7EJLDOWmkK+VTvVYUGp9hBDn0bFQTOdm/QVakCl/baQC2DMv7+yd8TLEGSJDU/NmwuKzESvSnA7QivIEKBbfBZfapcVLKrbp48MIFXldtmtLzvmd9pKdg15TQIOfVpPvi324KTuUDrQSKQUzrEMfMMMUSzNMTuLvEwnXxI19un2dD73xK/kJQEj9O6tVzEJFu5Y="
branches:
  only: master